jonhue/notifications-rails

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> [#5] Add issue templates

- notification-settings/lib/notification_settings/notification_library.rb
> [#14] Calling default_category on NotificationRenderer.configuration

- notification-renderer/app/helpers/notification_renderer_helper.rb
> [#15] render_notifications not working

- PULL_REQUEST_TEMPLATE.md
> [#9] Update pull request template

- CONTRIBUTING.md
> [#10] Update contribution guidelines

- CODE_OF_CONDUCT.md
> [#11] Update code of conduct

- README.md
- notifications-rails.gemspec
> [#8] Update README.md

- README.md
> [#22] Fix link to GitHub project in Readme

- README.md
> [#24] Remove License from Table of Contents (Readme)

- notification-settings/lib/notification_settings/notification_library.rb
> [#35] Treat notifications to be enabled by default

- notification-settings/lib/notification_settings/target.rb
> [#33] Automatically build `notification_setting` if object doesn't have one yet

- notification-settings/README.md
- notification-settings/lib/notification_settings/notification_library.rb
> [#45] Fix errors in initialize_pusher

- notification-pusher/Changelog.md
- notification-pusher/lib/notification_pusher/notification_library.rb
- notification-pusher/lib/notification_pusher/pusher.rb
- notification-pusher/notification-pusher-actioncable/lib/notification_pusher/action_cable.rb
- notification-pusher/notification-pusher-actionmailer/lib/notification_pusher/action_mailer.rb
- notification-pusher/notification-pusher-onesignal/lib/notification_pusher/one_signal.rb
> [#49] Change pushers to not immediately push when initialized

- .travis.yml
- notifications-rails.gemspec
> [#72] Fix travis

- .automerge.yml
> [#77] Enable auto merge

- notification-handler/notification-handler.gemspec
- notification-pusher/notification-pusher-actioncable/notification-pusher-actioncable.gemspec
- notification-pusher/notification-pusher-actionmailer/notification-pusher-actionmailer.gemspec
- notification-pusher/notification-pusher.gemspec
- notification-renderer/notification-renderer.gemspec
- notification-settings/notification-settings.gemspec
> [#60] Rails 5.1 support

- notification-pusher/notification-pusher-actionmailer/lib/notification_pusher/delivery_method/action_mailer.rb
> [#48] `deliver` not called on `NotificationMailer.push`

- .travis.yml
- CHANGELOG.md
- README.md
- notification-pusher/README.md
- notification-pusher/lib/generators/templates/install/initializer.rb
- notification-pusher/lib/notification_pusher/configuration.rb
- notification-pusher/lib/notification_pusher/delivery_method_configuration.rb
- notification-pusher/lib/notification_pusher/notification_lib.rb
- notification-pusher/notification-pusher-actionmailer/README.md
- notification-pusher/notification-pusher-onesignal/README.md
- notification-pusher/spec/lib/notification_pusher/configuration_spec.rb
- notification-pusher/spec/lib/notification_pusher/notification_lib_spec.rb
- notification-pusher/spec/support/rails_app/config/initializers/notification_pusher.rb
- notification-settings/spec/lib/notification_settings/notification_lib_spec.rb
- scripts/ci
- scripts/test
- spec/notification_settings_spec.rb
- spec/support/rails_app/config/initializers/notification_pusher.rb
> [#51] Swappable pushers (separate pusher name/key from pusher class)

- notification-handler/README.md
- notification-handler/lib/notification_handler/configuration.rb
- notification-handler/lib/notification_handler/group.rb
- notification-handler/lib/notification_handler/notification_lib.rb
- notification-handler/spec/lib/notification_handler/configuration_spec.rb
- notification-handler/spec/lib/notification_handler/notification_lib_spec.rb
- notification-handler/spec/support/rails_app/config/initializers/notification_handler.rb
- notification-pusher/README.md
- notification-pusher/lib/notification_pusher/configuration.rb
- notification-pusher/lib/notification_pusher/delivery_method_configuration.rb
- notification-pusher/notification-pusher-actionmailer/README.md
- notification-pusher/notification-pusher-onesignal/README.md
- notification-renderer/README.md
- notification-settings/README.md
> [#52] Allow Notification#target to be optional to allow more flexible sending to a dynamic "group"

- .github/auto-merge.yml
> [#97] Allow automatic merging without approving reviews

- CHANGELOG.md
- notification-pusher/notification-pusher-actionmailer/README.md
- notification-pusher/notification-pusher-actionmailer/app/mailers/notification_pusher/action_mailer/notification_mailer.rb
- notification-pusher/notification-pusher-actionmailer/lib/notification_pusher/delivery_method/action_mailer.rb
- notification-pusher/notification-pusher-actionmailer/notification-pusher-actionmailer.gemspec
- notification-pusher/spec/notification_pusher_general_spec.rb
- notification-renderer/app/helpers/notification_renderer_helper.rb
> [#53] Add an ActionMailer notification-pusher that lets you use existing mailers and templates

- notification-handler/README.md
- notification-handler/lib/notification_handler/object.rb
- notification-handler/lib/notification_handler/target.rb
> [#105] Complete documentation of notification_target & notification_object

- notification-handler/lib/generators/notification_handler/install_generator.rb
- notification-renderer/lib/generators/notification_renderer/install_generator.rb
- notification-renderer/lib/generators/templates/type/_template.html
- notification-settings/lib/generators/notification_settings/install_generator.rb
> [#107] notification-renderers type generator template not rendering example properly

- CHANGELOG.md
- notification-handler/README.md
- notification-handler/lib/generators/notification_handler/install_generator.rb
- notification-handler/lib/notification_handler/notification_lib.rb
- notification-handler/spec/factories/notifications.rb
- notification-handler/spec/lib/notification_handler/notification_lib_spec.rb
- notification-handler/spec/support/rails_app/config/initializers/notification_handler.rb
- notification-pusher/spec/factories/notifications.rb
- notification-renderer/README.md
- notification-renderer/lib/generators/notification_renderer/install_generator.rb
- notification-settings/lib/generators/notification_settings/install_generator.rb
> [#108] Creating a notification using group, will return single notification

- README.md
> [#126] Remove badges from readme

- .rubocop.yml
- notification-renderer/spec/helpers/notification_renderer_helper_spec.rb
> [#179] Fix rubocop offenses

- .github/workflows/ci.yml
> [#182] Enable CI for pull requests from forked repositories

- .github/workflows/ci.yml
- Gemfile.lock
Getting this to run green required updating nokogiri and sqlite3.  Everything runs green on my fork.
> Adds Ruby 3.2 to the CI matrix.
